// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDEcUg6YtUs0EhnpNBI_o2BIWK71kVEDo',
    appId: '1:65229343084:web:ad1b59c27d3e0f68960b49',
    messagingSenderId: '65229343084',
    projectId: 'skkn-auth',
    authDomain: 'skkn-auth.firebaseapp.com',
    storageBucket: 'skkn-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuEQTbdTU2GfLRrQhw8xcsTtI7Ahxay4E',
    appId: '1:65229343084:android:da1d0ff9940ca2ee960b49',
    messagingSenderId: '65229343084',
    projectId: 'skkn-auth',
    storageBucket: 'skkn-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwU_vYX-rTOOa1ABmPSTrrKhwWoPaYX9A',
    appId: '1:65229343084:ios:5969188635513212960b49',
    messagingSenderId: '65229343084',
    projectId: 'skkn-auth',
    storageBucket: 'skkn-auth.appspot.com',
    iosBundleId: 'com.example.skkn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwU_vYX-rTOOa1ABmPSTrrKhwWoPaYX9A',
    appId: '1:65229343084:ios:5969188635513212960b49',
    messagingSenderId: '65229343084',
    projectId: 'skkn-auth',
    storageBucket: 'skkn-auth.appspot.com',
    iosBundleId: 'com.example.skkn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDEcUg6YtUs0EhnpNBI_o2BIWK71kVEDo',
    appId: '1:65229343084:web:a810d6d61f73d152960b49',
    messagingSenderId: '65229343084',
    projectId: 'skkn-auth',
    authDomain: 'skkn-auth.firebaseapp.com',
    storageBucket: 'skkn-auth.appspot.com',
  );
}
